# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chipView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chipView
pod 'Material', '~> 3.1.0'

  target 'chipViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chipViewUITests' do
    # Pods for testing
  end

end
